#pragma once

#define CHAT_SOCKET_FILEPATH "chat.socket"
#define DATABASE_FILEPATH "userAccounts.db"
#define DATABASE_TABLE_PLAYERS "Players"
#define PORT "1337"  // the port users will be connecting to
#define DATABASE_TABLE_PLAYERS_ACCOUNTNAME_MAXLENGTH 32 //WARNING! IF THIS VALUE IS EVER CHANGED THE #define DATABASE_TABLE_PLAYERS_DEFINITION MUST BE CHANGED TOO
#define DATABASE_TABLE_PLAYERS_PASSWORD_MAXLENGTH 72
#define BCRYPT_SALT_PREFIX "$2y$" //"YOU CAN'T BASH THE HASH"
#define BCRYPT_SALT_ROUNDS "10$"
#define BCRYPT_SALT_PREFIX_AND_ROUNDS_CHARLENGTH 7
#define DATABASE_TABLE_PLAYERS_PASSWORDSALT_LENGTH 22
#define DATABASE_TABLE_PLAYERS_PASSWORDHASH_LENGTH 32 //WARNING! IF THIS VALUE IS EVER CHANGED #define DATABASE_TABLE_PLAYERS_DEFINITION MUST BE CHANGED TOO
#define DATABASE_TABLE_PLAYERS_DEFINITION "ID INTEGER PRIMARY KEY, accountName VARCHAR(32), password CHAR(32), salt CHAR(22), health INT" //WARNING!! THIS INCLUDES THE MAXLENGTH AND LENGTH OF ACCOUNTNAME AND PASSWORD FIELDS, IF THAT IS EVER CHANGED THIS WILL HAVE TO BE CHANGED TOO. This will probably have to be changed if the database engine is switched for another one
#define PASSWORD_COL 2 //Reference: "The leftmost column of the result set has the index 0." - https://www.sqlite.org/c3ref/column_blob.html
#define SALT_COL 3
#define HEALTH_COL 4
#define DATABASE_MAX_WRITE_ATTEMPTS 10
#define DATABASE_FAILED_WRITE_ATTEMPT_SLEEP_SECONDS 1
#define EMAIL_CRITICAL_ERROR "" //Removed due to fear of email crawlers
#define EPOLL_MAX_EVENTS 15
//const unsigned int MESSAGE_MAX_BYTESIZE = 1024;
#define MESSAGE_MAX_BYTESIZE  1024
#define FTOK_FILEPATH "some_file"
#define RECV_TIMEOUT_SEC 30
#define RECV_TIMEOUT_MICROSEC 0
#define RESERVED_SERVER_ANSWER_FOR_ERRORS_ON_THE_CLIENT 0 //NEVER USE 0 AS AN ANSWER BY THE SERVER, IT'S RESERVED
#define	PROTOCOL_VERSION_CURRENT 1
#define PROTOCOL_HANDSHAKE_OK 100
#define PROTOCOL_HANDSHAKE_UPGRADE 200
#define LOGIN_SUCESS 1100
#define LOGIN_ACCOUNT_DOESNT_EXIST 1200
#define LOGIN_WRONG_PASSWORD 1300
#define MSGCODE_CHAT_BROADCAST_MESSAGE 2000
